[general]
name = "Сумма чисел"

[limits]
time_limit_ms = 1000
memory_limit_mb = 32

[checker]
path = "checker"

[tests]
path = "tests"

[[test_groups]]
type = "sample"
tests = [0]
score = 0

[[test_groups]]
type = "main"
tests = [1, 2]
score = 100