[general]
name = "Сумма чисел"

[limits]
time_limit_ms = 1000
memory_limit_mb = 32

[checker]
path = "checker"

[[test_groups]]
type = "sample"
tests = ["tests/0"]
score = 0

[[test_group]]
type = "main"
tests = ["tests/1", "tests/2"]
score = 100