[package]
name = "ada-judge"
version = "0.2.0"
edition = "2024"
rust-version = "1.94.0"

[dependencies]
axum = { workspace = true, features = ["json"] }
solutions-judger.workspace = true
contests-manager.workspace = true
tokio.workspace = true
sqlx.workspace = true
models.workspace = true
apalis.workspace = true
apalis-postgres.workspace = true

[workspace]
members = ["crates/solutions-judger", "crates/contests-manager", "crates/models", "crates/tests"]
resolver = "3"

[workspace.dependencies]
solutions-judger = { path = "crates/solutions-judger" }
contests-manager = { path = "crates/contests-manager" }
models = { path = "crates/models"}
axum = "0.8.8"
tokio = { version = "1.50.0", features = ["rt-multi-thread"] }
sqlx = { version = "0.8.6", features = ["postgres"] }
apalis-postgres = "1.0.0-rc.4"
apalis = "1.0.0-rc.4"
serde = { version = "1.0.228", features = ["derive"] }
