[package]
name = "ada-judge"
version = "0.2.0"
edition = "2024"
rust-version = "1.94.0"

[dependencies]
solutions-judger.workspace = true

[workspace]
members = ["crates/solutions-judger", "crates/contests-manager", "crates/tests"]
resolver = "3"

[workspace.dependencies]
solutions-judger = { path = "crates/solutions-judger" }
contests-manager = { path = "crates/contests-manager" }
