services:
  postgres:
    image: postgres:18.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ada-judge
      POSTGRES_PASSWORD: ada-judge
      POSTGRES_DB: ada-judge
    ports:
      - "3333:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  sandbox-runner:
    build: ./containers/sandbox-runner
  main:
    build: 
      dockerfile: ./containers/main/Dockerfile
      context: .
    depends_on:
      - postgres
      - sandbox-runner
    environment:
      DATABASE_URL: postgres://ada-judge:ada-judge@postgres:5432/ada-judge
      HOST_RUNS_DIR: ${PWD}
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runs:/runs
volumes:
  pgdata:
