services:
  postgres:
    image: postgres:18.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/18/docker
  redis:
    image: redis:8-alpine
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 1s
      retries: 20
    environment:
      REDIS_USER: ${REDIS_USER}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER_PASSWORD: ${REDIS_USER_PASSWORD}
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redisdata:/data
  sandbox:
    build: ./containers/sandbox
    image: docker.io/oneprogboy/ada-judge-sandbox:latest
  submissions-judger:
    build:
      dockerfile: ./containers/app/Dockerfile
      context: .
      target: submissions-judger
    image: docker.io/oneprogboy/ada-judge-submissions-judger:latest
    group_add:
      - ${DOCKER_GID}
    deploy:
      replicas: ${WORKERS_COUNT}
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
      sandbox:
        condition: service_started
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://${REDIS_USER}:${REDIS_USER_PASSWORD}@redis:6379/0
      HOST_RUNS_DIR: ${PWD}
      SANDBOX_IMAGE: ada-judge-sandbox
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./submissions_envs:/submissions_envs
      - ./problems:/problems
  main:
    build:
      dockerfile: ./containers/app/Dockerfile
      context: .
      target: main
    image: docker.io/oneprogboy/ada-judge-main:latest
    group_add:
      - ${DOCKER_GID}
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
      sandbox:
        condition: service_started
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://${REDIS_USER}:${REDIS_USER_PASSWORD}@redis:6379/0
      HOST_RUNS_DIR: ${PWD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXP_HOURS: ${JWT_EXP_HOURS}
      SANDBOX_IMAGE: ada-judge-sandbox
    ports:
      - "4444:4444"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./submissions_envs:/submissions_envs
      - ./problems:/problems
volumes:
  pgdata:
  redisdata:
