[package]
name = "tests"
version = "0.0.0"
edition = "2024"
publish = false

[dev-dependencies]
submissions-judger.workspace = true
models.workspace = true
axum.workspace = true
sqlx.workspace = true
apalis.workspace = true
tokio.workspace = true
log.workspace = true
pretty-logging.workspace = true

[[test]]
name = "tests"
path = "tests.rs"

[dependencies]
tempfile = "3.27.0"
aj-models.workspace = true
