[package]
name = "solutions-judger"
version = "0.0.0"
edition = "2024"

[dependencies]
fs_extra = "1.3.0"
toml = "1.0.6"
wait-timeout = "0.2.1"
axum.workspace = true
tokio.workspace = true
sqlx.workspace = true
models.workspace = true
apalis.workspace = true
apalis-postgres.workspace = true
serde.workspace = true