name = "Сумма чисел III"
contest_id = 1
problem_index = 2
time_limit_ms = 1000
memory_limit_mb = 10
checker_path = "checker"
tests_path = "tests"
is_interactive = false

[[subgroups]]
type = "sample"
tests = [0]
score = 0
depends_on = []

[[subgroups]]
type = "main"
tests = [1, 2]
score = 100
depends_on = [179]
