name_ru = "Сумма чисел V"
name_en = "Sum of numbers V"
type = "default"
merge_subgroups = false
contest_id = 1
problem_index = 4
time_limit_ms = 1000
memory_limit_mb = 256
checker_path = "checker"
tests_path = "tests"

[[subgroups]]
type = "sample"
tests = [0]
score = 0
depends_on = []

[[subgroups]]
type = "main"
tests = [1, 2]
score_per_test = 50
depends_on = [0]
